# Generated by Django 5.2 on 2025-05-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_application_delete_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reason',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
