# Generated by Django 5.2 on 2025-05-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_performanceevaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performanceevaluation',
            name='employee',
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='employee_name',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
